<?php
require_once dirname(__DIR__).'/src/config.php';require_once RUTA.'/src/autoload.php';
use AppBancos\Application\EjecutorComandoIdempotente;use AppBancos\Application\GuardarReglaAsignacion;use AppBancos\Application\RetirarReglaAsignacion;use AppBancos\Infrastructure\EsquemaBancos;use AppBancos\Repository\AuditoriaRepository;use AppBancos\Repository\IdempotenciaRepository;use AppBancos\Repository\ImportacionExtractoRepository;use AppBancos\Repository\ReglaAsignacionRepository;
function comprobarAsignacion($c,$m){if(!$c){throw new RuntimeException($m);}}
$pdo=new PDO('pgsql:host='.HOST.';port='.PORT.';dbname='.DBASE,USER,PASS,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$esquema=EsquemaBancos::desdeConfiguracion(['bancos_debug'=>true]);$repo=new ReglaAsignacionRepository($pdo,$esquema);$usuarios=$repo->listarResponsablesElegibles();
$contexto=$pdo->query("SELECT cc.configuracion_id::text,cc.cuenta_bancaria_zetti_id::text FROM global_temp.bancos_configuracion_cuenta cc WHERE cc.activo IS TRUE ORDER BY cc.id LIMIT 1")->fetch(PDO::FETCH_ASSOC);
$subtipo=(string)$pdo->query("SELECT sv.id FROM public.subtipo_valor sv WHERE NOT EXISTS(SELECT 1 FROM global_temp.bancos_regla_asignacion_usuario r WHERE r.configuracion_id=".(int)$contexto['configuracion_id']." AND r.subtipo_valor_zetti_id=sv.id) ORDER BY sv.id LIMIT 1")->fetchColumn();
$operador=(int)$pdo->query("SELECT id FROM global_prod.rrhh_login WHERE lower(usuario)='mcaballero' AND habilitado IS TRUE AND fecha_eliminacion IS NULL")->fetchColumn();
comprobarAsignacion($contexto!==false&&$subtipo!==''&&count($usuarios)>=2&&$operador>0,'Falta contexto para probar reglas de asignacion.');
$marca=bin2hex(random_bytes(8));$claves=['crear'=>'test-asignacion-crear-'.$marca,'versionar'=>'test-asignacion-versionar-'.$marca,'retirar'=>'test-asignacion-retirar-'.$marca];$ejecutor=new EjecutorComandoIdempotente($pdo,new IdempotenciaRepository($pdo,$esquema),new AuditoriaRepository($pdo,$esquema));$guardar=new GuardarReglaAsignacion($repo,$ejecutor);$retirar=new RetirarReglaAsignacion($repo,$ejecutor);$ids=[];$importacionId=null;
try{
 $entrada=['configuracion_id'=>$contexto['configuracion_id'],'regla_asignacion_id'=>null,'subtipo_valor_zetti_id'=>(int)$subtipo,'usuario_id'=>$usuarios[0]['id'],'motivo'=>'Alta aislada de responsable automatico'];$a=$guardar->ejecutar($entrada,$operador,$claves['crear']);$rep=$guardar->ejecutar($entrada,$operador,$claves['crear']);$ids[]=$a['respuesta']['regla_asignacion_id'];comprobarAsignacion($a['codigo_http']===201&&$a['respuesta']['version']===1&&$rep['repetida']===true,'El alta no cumple version e idempotencia.');
 $entrada['regla_asignacion_id']=$ids[0];$entrada['usuario_id']=$usuarios[1]['id'];$entrada['motivo']='Cambio aislado de responsable automatico';$v=$guardar->ejecutar($entrada,$operador,$claves['versionar']);$ids[]=$v['respuesta']['regla_asignacion_id'];comprobarAsignacion($v['respuesta']['version']===2&&$v['respuesta']['regla_asignacion_id_anterior']===$ids[0],'No se encadeno la nueva version.');
 $pdo->beginTransaction();$respuesta=(new ImportacionExtractoRepository($pdo,$esquema))->crearLote($contexto['configuracion_id'],$contexto['cuenta_bancaria_zetti_id'],'2099-01-01','test-'.$marca.'.csv',hash('sha256',$marca),'TEST-ASIGNACION-'.$marca,[['numero_fila_origen'=>2,'fecha_operacion'=>'2099-01-02','referencia'=>'TEST','descripcion'=>'Asignacion automatica','codigo_extracto'=>'TEST','credito'=>'1.00000','debito'=>'0.00000','subtipo_valor_zetti_id'=>(int)$subtipo]],$operador,'test-import-'.$marca);$importacionId=$respuesta['importacion_id'];$pdo->commit();
 comprobarAsignacion($respuesta['asignados_automaticamente']===1,'La importacion no informo la asignacion automatica.');$q=$pdo->prepare("SELECT h.usuario_hub_id::text,e.codigo FROM global_temp.bancos_historial_asignacion h JOIN global_temp.bancos_movimiento_extracto m ON m.id=h.movimiento_id JOIN global_temp.bancos_estado e ON e.id=h.estado_id WHERE m.importacion_id=:id");$q->execute([':id'=>$importacionId]);$h=$q->fetch(PDO::FETCH_ASSOC);comprobarAsignacion($h!==false&&$h['usuario_hub_id']===$usuarios[1]['id']&&$h['codigo']==='ABIERTO','Se asigno otro usuario o estado.');
 $b=$retirar->ejecutar(['configuracion_id'=>$contexto['configuracion_id'],'regla_asignacion_id'=>$ids[1],'motivo'=>'Retiro aislado de responsable automatico'],$operador,$claves['retirar']);comprobarAsignacion($b['respuesta']['activo']===false,'No se retiro la regla.');
 $permiso=$pdo->query("SELECT count(DISTINCT p.id) permisos,count(pu.id) asignaciones FROM global_prod.hub_permisos p LEFT JOIN global_prod.hub_permisos_usuario pu ON pu.permiso=p.id AND pu.ignorado IS NULL WHERE p.origen_id='app_bancos:accion:configuracion-administrar-asignaciones' AND p.ignorado IS NULL")->fetch(PDO::FETCH_ASSOC);comprobarAsignacion((int)$permiso['permisos']===1&&(int)$permiso['asignaciones']===0,'El permiso granular no cumple el contrato.');
 $vista=file_get_contents(dirname(__DIR__).'/app/html/configuraciones.php');$js=file_get_contents(dirname(__DIR__).'/app/js/shared.js');$api=file_get_contents(dirname(__DIR__).'/api.php');foreach(['data-editor-asignacion','data-editar-asignacion','data-retirar-asignacion']as$f){comprobarAsignacion(strpos($vista,$f)!==false,'Falta contrato visual: '.$f);}foreach(['configuracion.guardar-asignacion','configuracion.retirar-asignacion','aplicarAsignacion']as$f){comprobarAsignacion(strpos($js,$f)!==false,'Falta contrato cliente: '.$f);}foreach(["'configuracion.guardar-asignacion'","'configuracion.retirar-asignacion'","'configuracion-administrar-asignaciones'"]as$f){comprobarAsignacion(strpos($api,$f)!==false,'Falta proteccion API: '.$f);}
}finally{
 $pdo->beginTransaction();if($importacionId!==null){$q=$pdo->prepare('DELETE FROM global_temp.bancos_historial_asignacion WHERE movimiento_id IN(SELECT id FROM global_temp.bancos_movimiento_extracto WHERE importacion_id=:id)');$q->execute([':id'=>$importacionId]);$q=$pdo->prepare('DELETE FROM global_temp.bancos_movimiento_extracto WHERE importacion_id=:id');$q->execute([':id'=>$importacionId]);$q=$pdo->prepare('DELETE FROM global_temp.bancos_importacion_extracto WHERE id=:id');$q->execute([':id'=>$importacionId]);}$q=$pdo->prepare("DELETE FROM global_temp.bancos_evento_auditoria WHERE solicitud_id IN(SELECT id FROM global_temp.bancos_solicitud_idempotente WHERE clave IN(:crear,:versionar,:retirar))");$q->execute($claves);$q=$pdo->prepare('DELETE FROM global_temp.bancos_solicitud_idempotente WHERE clave IN(:crear,:versionar,:retirar)');$q->execute($claves);foreach(array_reverse($ids)as$id){$q=$pdo->prepare('DELETE FROM global_temp.bancos_regla_asignacion_usuario WHERE id=:id');$q->execute([':id'=>$id]);}$pdo->commit();
}
echo "Reglas de asignacion automatica debug OK\n";
