-- Migración 012. Cada fase confirma sus datos y deja métricas persistentes.
-- Consultar 012_bancos_monitorear.sql desde otra sesión durante la ejecución.
CREATE TABLE IF NOT EXISTS global_prod.bancos_migracion_ejecucion (
 migracion varchar(40) NOT NULL, fase varchar(80) NOT NULL,
 estado varchar(20) NOT NULL CHECK (estado IN ('EN_CURSO','OK','ERROR')),
 inicio_en timestamptz NOT NULL DEFAULT now(), fin_en timestamptz,
 filas_afectadas bigint, detalle text, PRIMARY KEY (migracion,fase)
);
CREATE TABLE IF NOT EXISTS global_prod.bancos_migracion_borrador_legacy (id_interno_asiento bigint PRIMARY KEY,borrador_asiento_id bigint REFERENCES global_prod.bancos_borrador_asiento(id));
CREATE TABLE IF NOT EXISTS global_prod.bancos_migracion_recurso_omitido (tipo_recurso varchar(20) NOT NULL CHECK (tipo_recurso IN ('VALOR','ASIENTO')), recurso_zetti_id bigint NOT NULL, id_movimiento_legacy varchar(100) NOT NULL, motivo text NOT NULL, PRIMARY KEY (tipo_recurso,recurso_zetti_id,id_movimiento_legacy));
CREATE TABLE IF NOT EXISTS global_prod.bancos_migracion_emisor_legacy (id_usuario_legacy varchar(100) PRIMARY KEY,login_id bigint REFERENCES global_prod.rrhh_login(id),metodo varchar(50) NOT NULL,observacion text);

-- 00: materializa e indexa los conjuntos reutilizados por las fases pesadas.
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','00_PREPARAR_CONJUNTOS','EN_CURSO',now(),'Materializando movimientos canónicos y agregados ERP.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
ALTER TABLE global_prod.bancos_mensaje_movimiento ALTER COLUMN emisor_hub_id DROP NOT NULL;
DROP TABLE IF EXISTS global_prod.bancos_migracion_012_movimiento_canonico;
CREATE TABLE global_prod.bancos_migracion_012_movimiento_canonico AS SELECT id_movimiento_legacy,movimiento_id,id_periodo_legacy,serial_seq_canonico FROM global_prod.bancos_migracion_movimiento_legacy WHERE es_canonico AND movimiento_id IS NOT NULL;
CREATE UNIQUE INDEX bancos_migracion_012_movimiento_canonico_pk ON global_prod.bancos_migracion_012_movimiento_canonico(id_movimiento_legacy);
CREATE INDEX bancos_migracion_012_movimiento_canonico_movimiento_idx ON global_prod.bancos_migracion_012_movimiento_canonico(movimiento_id);
DROP TABLE IF EXISTS global_prod.bancos_migracion_012_asiento_semantica;
CREATE TABLE global_prod.bancos_migracion_012_asiento_semantica AS SELECT id_asiento,bool_or(COALESCE(mult_asiento,false)) compartido FROM public.bancos_mes_asiento_asignado_movimiento WHERE id_asiento<>0 GROUP BY id_asiento;
CREATE UNIQUE INDEX bancos_migracion_012_asiento_semantica_pk ON global_prod.bancos_migracion_012_asiento_semantica(id_asiento);
DROP TABLE IF EXISTS global_prod.bancos_migracion_012_asiento_importe;
CREATE TABLE global_prod.bancos_migracion_012_asiento_importe AS SELECT asiento id_asiento,max(abs(monto)) importe FROM public.movimiento GROUP BY asiento;
CREATE UNIQUE INDEX bancos_migracion_012_asiento_importe_pk ON global_prod.bancos_migracion_012_asiento_importe(id_asiento);
DROP TABLE IF EXISTS global_prod.bancos_migracion_012_asiento_exclusion;
CREATE TABLE global_prod.bancos_migracion_012_asiento_exclusion AS SELECT id_asiento,count(*) filas FROM public.bancos_mes_exclusiones WHERE id_asiento IS NOT NULL AND id_asiento<>0 GROUP BY id_asiento;
CREATE UNIQUE INDEX bancos_migracion_012_asiento_exclusion_pk ON global_prod.bancos_migracion_012_asiento_exclusion(id_asiento);
-- Índices de las claves usadas por el rollback. Se crean antes de cargar 012,
-- por lo que también se mantienen durante los inserts posteriores.
CREATE INDEX IF NOT EXISTS bancos_linea_borrador_asiento_borrador_idx ON global_prod.bancos_linea_borrador_asiento(borrador_asiento_id);
CREATE INDEX IF NOT EXISTS bancos_asociacion_movimiento_borrador_idx ON global_prod.bancos_asociacion_movimiento(borrador_asiento_id);
CREATE INDEX IF NOT EXISTS bancos_reserva_recurso_borrador_idx ON global_prod.bancos_reserva_recurso(borrador_asiento_id);
CREATE INDEX IF NOT EXISTS bancos_reserva_recurso_012_observacion_idx ON global_prod.bancos_reserva_recurso(observacion) WHERE observacion='MIGRACION-012|EXCLUSION';
CREATE INDEX IF NOT EXISTS bancos_asociacion_movimiento_012_observacion_idx ON global_prod.bancos_asociacion_movimiento(observacion) WHERE observacion IN ('MIGRACION-012|VALOR','MIGRACION-012|ASIENTO');
UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM global_prod.bancos_migracion_012_movimiento_canonico),detalle='Conjunto canónico indexado y agregados preparados.' WHERE migracion='012' AND fase='00_PREPARAR_CONJUNTOS';
COMMIT;

-- 01: reglas de negocio y preflight, antes de modificar dependencias.
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','01_PREFLIGHT','EN_CURSO',now(),'Validando valores duplicados, cuentas y emisores.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
INSERT INTO global_prod.bancos_migracion_emisor_legacy(id_usuario_legacy,login_id,metodo,observacion) VALUES ('1003',34,'ALIAS_LOGIN_USERS','NCAROL'),('1007',307,'ALIAS_LOGIN_USERS','CMARCHANT'),('1001',NULL,'SIN_EMISOR','Usuario legacy eliminado; se conserva como mensaje de sistema.') ON CONFLICT(id_usuario_legacy) DO UPDATE SET login_id=EXCLUDED.login_id,metodo=EXCLUDED.metodo,observacion=EXCLUDED.observacion;
INSERT INTO global_prod.bancos_migracion_recurso_omitido(tipo_recurso,recurso_zetti_id,id_movimiento_legacy,motivo) VALUES ('VALOR',103500000012894309,'M000685P1911680119736062020','Duplicación o rectificación operativa de cheque 57137580; se conserva la imputación previa del 16/03/2020.') ON CONFLICT DO NOTHING;
INSERT INTO global_prod.bancos_migracion_recurso_omitido(tipo_recurso,recurso_zetti_id,id_movimiento_legacy,motivo)
SELECT DISTINCT 'ASIENTO',a.id_asiento,a.id_movimiento,CASE WHEN i.importe IS NULL THEN 'Asiento sin líneas ERP: no se puede validar la asociación bancaria.' ELSE 'Importe bancario distinto del importe del asiento ERP; se conserva sólo la coincidencia exacta.' END FROM public.bancos_mes_asiento_asignado_movimiento a JOIN global_prod.bancos_migracion_012_asiento_semantica s ON s.id_asiento=a.id_asiento AND NOT s.compartido LEFT JOIN global_prod.bancos_migracion_012_asiento_importe i ON i.id_asiento=a.id_asiento JOIN public.bancos_mes_movimientos_cargados_periodo m ON m.id_movimiento=a.id_movimiento WHERE i.importe IS NULL OR abs(COALESCE(m.debito,0)+COALESCE(m.credito,0))<>i.importe ON CONFLICT DO NOTHING;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM public.bancos_mes_valor_asignado_movimiento v JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=v.id_movimiento LEFT JOIN global_prod.bancos_migracion_recurso_omitido o ON o.tipo_recurso='VALOR' AND o.recurso_zetti_id=v.id_valor AND o.id_movimiento_legacy=v.id_movimiento WHERE o.id_movimiento_legacy IS NULL GROUP BY v.id_valor HAVING count(DISTINCT t.movimiento_id)>1) THEN RAISE EXCEPTION 'Hay valores ERP asociados a más de un movimiento; resolverlos antes de la migración'; END IF;
 IF EXISTS(WITH l AS (SELECT l.id_interno_asiento,COALESCE(NULLIF(btrim(l.codigo_cuenta),''),(SELECT min(l2.codigo_cuenta) FROM public.bancos_mes_movimientos_creados_asiento l2 WHERE l2.id_interno_asiento=l.id_interno_asiento AND NULLIF(btrim(l2.codigo_cuenta),'') IS NOT NULL AND lower(btrim(l2.nombre))=lower(btrim(l.nombre)) AND l2.debe=l.haber AND l2.haber=l.debe HAVING count(DISTINCT l2.codigo_cuenta)=1)) codigo FROM public.bancos_mes_movimientos_creados_asiento l) SELECT 1 FROM l WHERE (SELECT count(*) FROM public.cuenta c WHERE c.codigo=l.codigo)<>1) THEN RAISE EXCEPTION 'Hay líneas de borrador sin cuenta ERP unívoca por código'; END IF;
 IF EXISTS(SELECT 1 FROM public.bancos_mensajeria m LEFT JOIN global_prod.bancos_migracion_emisor_legacy e ON e.id_usuario_legacy=m.id_usuario_emisor WHERE e.id_usuario_legacy IS NULL) THEN RAISE EXCEPTION 'Hay mensajes legacy sin emisor mapeado'; END IF;
END $$;
UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=0,detalle='Preflight superado.' WHERE migracion='012' AND fase='01_PREFLIGHT'; COMMIT;

-- 02 y 03: asociaciones. Las CTE insertan y registran la cantidad en la misma fase.
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','02_ASOCIACIONES_VALOR','EN_CURSO',now(),'Insertando asociaciones a valores.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
WITH ins AS (INSERT INTO global_prod.bancos_asociacion_movimiento(movimiento_id,valor_zetti_id,monto_asociado,observacion) SELECT t.movimiento_id,v.id_valor,NULLIF(abs(v.monto_asignado)::numeric(20,5),0),'MIGRACION-012|VALOR' FROM public.bancos_mes_valor_asignado_movimiento v JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=v.id_movimiento JOIN public.valor x ON x.id=v.id_valor LEFT JOIN global_prod.bancos_migracion_recurso_omitido o ON o.tipo_recurso='VALOR' AND o.recurso_zetti_id=v.id_valor AND o.id_movimiento_legacy=v.id_movimiento WHERE o.id_movimiento_legacy IS NULL AND NOT EXISTS(SELECT 1 FROM global_prod.bancos_asociacion_movimiento z WHERE z.movimiento_id=t.movimiento_id AND z.valor_zetti_id=v.id_valor AND z.observacion='MIGRACION-012|VALOR') RETURNING 1) UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM ins),detalle='Asociaciones a valores confirmadas.' WHERE migracion='012' AND fase='02_ASOCIACIONES_VALOR'; COMMIT;
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','03_ASOCIACIONES_ASIENTO','EN_CURSO',now(),'Insertando asociaciones a asientos.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
WITH ins AS (INSERT INTO global_prod.bancos_asociacion_movimiento(movimiento_id,asiento_zetti_id,monto_asociado,compartido,observacion) SELECT t.movimiento_id,a.id_asiento,NULLIF(abs(a.monto_asignado)::numeric(20,5),0),s.compartido,'MIGRACION-012|ASIENTO' FROM public.bancos_mes_asiento_asignado_movimiento a JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=a.id_movimiento JOIN public.asiento x ON x.id=a.id_asiento JOIN global_prod.bancos_migracion_012_asiento_semantica s ON s.id_asiento=a.id_asiento LEFT JOIN global_prod.bancos_migracion_recurso_omitido o ON o.tipo_recurso='ASIENTO' AND o.recurso_zetti_id=a.id_asiento AND o.id_movimiento_legacy=a.id_movimiento WHERE o.id_movimiento_legacy IS NULL AND NOT EXISTS(SELECT 1 FROM global_prod.bancos_asociacion_movimiento z WHERE z.movimiento_id=t.movimiento_id AND z.asiento_zetti_id=a.id_asiento AND z.observacion='MIGRACION-012|ASIENTO') RETURNING 1) UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM ins),detalle='Asociaciones a asientos confirmadas.' WHERE migracion='012' AND fase='03_ASOCIACIONES_ASIENTO'; COMMIT;

-- 04 y 05: reservas.
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','04_RESERVAS_VALOR','EN_CURSO',now(),'Insertando reservas a valores.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
WITH ins AS (INSERT INTO global_prod.bancos_reserva_recurso(movimiento_id,valor_zetti_id,fecha_creacion,observacion) SELECT t.movimiento_id,e.id_valor,COALESCE(e.timestamp AT TIME ZONE 'America/Argentina/Buenos_Aires',now()),'MIGRACION-012|EXCLUSION' FROM public.bancos_mes_exclusiones e JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=e.id_movimiento JOIN public.valor x ON x.id=e.id_valor WHERE e.id_valor IS NOT NULL AND NOT EXISTS(SELECT 1 FROM global_prod.bancos_reserva_recurso z WHERE z.movimiento_id=t.movimiento_id AND z.valor_zetti_id=e.id_valor AND z.observacion='MIGRACION-012|EXCLUSION') RETURNING 1) UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM ins),detalle='Reservas a valores confirmadas.' WHERE migracion='012' AND fase='04_RESERVAS_VALOR'; COMMIT;
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','05_RESERVAS_ASIENTO','EN_CURSO',now(),'Insertando reservas a asientos.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
WITH ins AS (INSERT INTO global_prod.bancos_reserva_recurso(movimiento_id,asiento_zetti_id,compartido,activo,fecha_creacion,observacion) SELECT t.movimiento_id,e.id_asiento,COALESCE(s.compartido,false),COALESCE(s.compartido,false) OR (COALESCE(q.filas,0)=1 AND COALESCE(abs(COALESCE(src.debito,0)+COALESCE(src.credito,0))=i.importe,false)),COALESCE(e.timestamp AT TIME ZONE 'America/Argentina/Buenos_Aires',now()),'MIGRACION-012|EXCLUSION' FROM public.bancos_mes_exclusiones e JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=e.id_movimiento JOIN public.asiento a ON a.id=e.id_asiento JOIN public.bancos_mes_movimientos_cargados_periodo src ON src.id_periodo=t.id_periodo_legacy AND src.serial_seq=t.serial_seq_canonico LEFT JOIN global_prod.bancos_migracion_012_asiento_semantica s ON s.id_asiento=e.id_asiento LEFT JOIN global_prod.bancos_migracion_012_asiento_importe i ON i.id_asiento=e.id_asiento LEFT JOIN global_prod.bancos_migracion_012_asiento_exclusion q ON q.id_asiento=e.id_asiento WHERE e.id_asiento IS NOT NULL AND e.id_asiento<>0 AND NOT EXISTS(SELECT 1 FROM global_prod.bancos_reserva_recurso z WHERE z.movimiento_id=t.movimiento_id AND z.asiento_zetti_id=e.id_asiento AND z.observacion='MIGRACION-012|EXCLUSION') RETURNING 1) UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM ins),detalle='Reservas a asientos confirmadas.' WHERE migracion='012' AND fase='05_RESERVAS_ASIENTO'; COMMIT;

-- 06: borradores. El CTE de líneas resuelve código de cuenta una vez por fila.
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','06_BORRADORES','EN_CURSO',now(),'Insertando borradores y líneas.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
INSERT INTO global_prod.bancos_borrador_asiento(movimiento_id,nodo_zetti_id,fecha_contable,estado_id,clave_idempotencia,modelo,observacion) SELECT t.movimiento_id,h.nodo_creacion::integer,h.fecha_creacion,1,'MIGRACION-012|BORRADOR|'||h.id_interno_asiento,h.asiento_modelo::text,left(h.nombre,200) FROM public.bancos_mes_asientos_creados_movimiento h JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=h.id_movimiento JOIN public.nodo n ON n.id=h.nodo_creacion::integer WHERE NOT EXISTS(SELECT 1 FROM global_prod.bancos_borrador_asiento b WHERE b.clave_idempotencia='MIGRACION-012|BORRADOR|'||h.id_interno_asiento);
INSERT INTO global_prod.bancos_migracion_borrador_legacy(id_interno_asiento,borrador_asiento_id) SELECT h.id_interno_asiento,b.id FROM public.bancos_mes_asientos_creados_movimiento h JOIN global_prod.bancos_borrador_asiento b ON b.clave_idempotencia='MIGRACION-012|BORRADOR|'||h.id_interno_asiento ON CONFLICT(id_interno_asiento) DO UPDATE SET borrador_asiento_id=EXCLUDED.borrador_asiento_id;
WITH lineas AS (SELECT l.*,COALESCE(NULLIF(btrim(l.codigo_cuenta),''),(SELECT min(l2.codigo_cuenta) FROM public.bancos_mes_movimientos_creados_asiento l2 WHERE l2.id_interno_asiento=l.id_interno_asiento AND NULLIF(btrim(l2.codigo_cuenta),'') IS NOT NULL AND lower(btrim(l2.nombre))=lower(btrim(l.nombre)) AND l2.debe=l.haber AND l2.haber=l.debe HAVING count(DISTINCT l2.codigo_cuenta)=1)) codigo FROM public.bancos_mes_movimientos_creados_asiento l),ins AS (INSERT INTO global_prod.bancos_linea_borrador_asiento(borrador_asiento_id,cuenta_zetti_id,debe,haber,observacion) SELECT mb.borrador_asiento_id,c.id,CASE WHEN l.haber<0 THEN abs(l.haber)::numeric(20,5) ELSE greatest(l.debe,0)::numeric(20,5) END,CASE WHEN l.debe<0 THEN abs(l.debe)::numeric(20,5) ELSE greatest(l.haber,0)::numeric(20,5) END,left(l.nombre,200) FROM lineas l JOIN global_prod.bancos_migracion_borrador_legacy mb ON mb.id_interno_asiento=l.id_interno_asiento JOIN public.cuenta c ON c.codigo=l.codigo WHERE (l.debe<>0 OR l.haber<>0) AND NOT EXISTS(SELECT 1 FROM global_prod.bancos_linea_borrador_asiento z WHERE z.borrador_asiento_id=mb.borrador_asiento_id AND z.cuenta_zetti_id=c.id AND z.debe=CASE WHEN l.haber<0 THEN abs(l.haber) ELSE greatest(l.debe,0) END AND z.haber=CASE WHEN l.debe<0 THEN abs(l.debe) ELSE greatest(l.haber,0) END AND z.observacion IS NOT DISTINCT FROM left(l.nombre,200)) RETURNING 1) UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM ins),detalle='Borradores y líneas confirmados.' WHERE migracion='012' AND fase='06_BORRADORES'; COMMIT;

-- 07: mensajes, aislados porque la tabla destino no tiene marca de origen.
INSERT INTO global_prod.bancos_migracion_ejecucion(migracion,fase,estado,inicio_en,detalle) VALUES ('012','07_MENSAJES','EN_CURSO',now(),'Insertando mensajes.') ON CONFLICT(migracion,fase) DO UPDATE SET estado='EN_CURSO',inicio_en=now(),fin_en=NULL,filas_afectadas=NULL,detalle=EXCLUDED.detalle;
BEGIN;
WITH ins AS (INSERT INTO global_prod.bancos_mensaje_movimiento(movimiento_id,emisor_hub_id,tipo_mensaje,cuerpo,emitido_en) SELECT t.movimiento_id,e.login_id,CASE WHEN e.login_id IS NULL OR m.mensaje_de_sistema<>0 THEN 'SISTEMA' ELSE 'USUARIO' END,m.mensaje,COALESCE(m.emision_time AT TIME ZONE 'America/Argentina/Buenos_Aires',now()) FROM public.bancos_mensajeria m JOIN global_prod.bancos_migracion_012_movimiento_canonico t ON t.id_movimiento_legacy=m.id_movimiento JOIN global_prod.bancos_migracion_emisor_legacy e ON e.id_usuario_legacy=m.id_usuario_emisor WHERE NOT EXISTS(SELECT 1 FROM global_prod.bancos_mensaje_movimiento z WHERE z.movimiento_id=t.movimiento_id AND z.emisor_hub_id IS NOT DISTINCT FROM e.login_id AND z.cuerpo IS NOT DISTINCT FROM m.mensaje AND z.emitido_en=COALESCE(m.emision_time AT TIME ZONE 'America/Argentina/Buenos_Aires',now())) RETURNING 1) UPDATE global_prod.bancos_migracion_ejecucion SET estado='OK',fin_en=now(),filas_afectadas=(SELECT count(*) FROM ins),detalle='Mensajes confirmados.' WHERE migracion='012' AND fase='07_MENSAJES'; COMMIT;
